// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvTytkyLzxYHQn0zOTf510AwUQqLlEzSc',
    appId: '1:300911385598:web:e4298788af8f21fec4beaf',
    messagingSenderId: '300911385598',
    projectId: 'tasklistdb-9b8f3',
    authDomain: 'tasklistdb-9b8f3.firebaseapp.com',
    databaseURL: 'https://tasklistdb-9b8f3-default-rtdb.firebaseio.com',
    storageBucket: 'tasklistdb-9b8f3.appspot.com',
    measurementId: 'G-LBYHSPQZX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPlsoyCoLVPS2LLs06y6gnhxYcSXnjAuU',
    appId: '1:300911385598:android:4d17c7b837cf291ec4beaf',
    messagingSenderId: '300911385598',
    projectId: 'tasklistdb-9b8f3',
    databaseURL: 'https://tasklistdb-9b8f3-default-rtdb.firebaseio.com',
    storageBucket: 'tasklistdb-9b8f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl-wgMMHh_H2D9KaOUhYjcNcxADQoEZoY',
    appId: '1:300911385598:ios:bdd9d1857a35df7bc4beaf',
    messagingSenderId: '300911385598',
    projectId: 'tasklistdb-9b8f3',
    databaseURL: 'https://tasklistdb-9b8f3-default-rtdb.firebaseio.com',
    storageBucket: 'tasklistdb-9b8f3.appspot.com',
    iosBundleId: 'com.example.taskListDb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl-wgMMHh_H2D9KaOUhYjcNcxADQoEZoY',
    appId: '1:300911385598:ios:3595fec1169fccc8c4beaf',
    messagingSenderId: '300911385598',
    projectId: 'tasklistdb-9b8f3',
    databaseURL: 'https://tasklistdb-9b8f3-default-rtdb.firebaseio.com',
    storageBucket: 'tasklistdb-9b8f3.appspot.com',
    iosBundleId: 'com.example.taskListDb.RunnerTests',
  );
}
